### ISSUE TITLE
Docker CI

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/FEniCS.jl#40]
https://github.com/tpapp/texlive-julia-minimal-docker

**Comment by ysimillides** [comment]
I'll have a closer look this weekend.
Regarding providijng a FEniCS install to the user, maybe, instead of providing the conda script, to let them install it on their own(depending on system etc), as [OpenCl.jl ](https://github.com/JuliaGPU/OpenCL.jl) suggests and then simply provide some instructions to find it with PyCall?

**Comment by ysimillides** [comment]
Docker images now exist, #49
